config/routes.rb
Rails.application.routes.draw do

  root 'public_pages#home'

  resources :patients

  match '/home', to: 'public_pages#home', via: 'get'
  match '/services', to: 'public_pages#services', via: 'get'
  match '/location', to: 'public_pages#location', via: 'get'

  match 'patient_record', to: 'patients#new', via: 'get'
  match 'patient_infos', to: 'patients#patient_info', via: 'post'
  match 'dental_insurances', to: 'patients#dental_insurance', via: 'post'
  match 'dental_histories', to: 'patients#dental_history', via: 'post'

  match 'lvd_employee_area77', to: 'private_pages#lakeview_emp_area77', via: 'get'
  match 'lvd_employee_area88', to: 'private_pages#lakeview_emp_area88', via: 'get'
  
  get 'lvd_emp_loggin' => 'lvd_priv_sessions#new'
  post 'lvd_emp_loggin' => 'lvd_priv_sessions#create'
  delete 'lvd_emp_logout' => 'lvd_priv_sessions#destroy'

end

app/controllers/lvd_priv_sessions_controller.rb
class LvdPrivSessionsController < ApplicationController

include PrivateHelper

def new
	
end

def create
	user = User.find_by(name: params[:lvd_priv_session][:name])
	if user && 
		user.authenticate(params[:lvd_priv_session][:password])
		loggin user
		flash[:success] = "Success"
		redirect_to lvd_employee_area77_path
	else
	flash.now[:danger] = "Invalid login information"
	render 'new'
	end
end

def waiting

end

def destroy
	
end

end

app/views/lvd_priv_sessions/new.html.erb
<% flash.each do |key, value| %>
	<div class="text-center alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="container">

<div class="well blue_back well_top text-center", id="formtop1">
	<h3 id="patient_info_topper">Employees Only Sign In Area </h3>
</div>
	<div class='well'>
	<%= bootstrap_form_for :lvd_priv_session, url: lvd_emp_loggin_path do |f| %>

		
		<%= f.text_field :name, placeholder: "Nombre..." %>
		<br>
		<%= f.password_field :password, placeholder: "Contraseña..." %>
		<br>
		<%= f.submit "Login", class: "btn btn-primary" %>
		
	<% end %>

	</div>
</div>