config/routes.rb
Rails.application.routes.draw do

  root 'public_pages#home'

  resources :patients

  match '/home', to: 'public_pages#home', via: 'get'
  match '/services', to: 'public_pages#services', via: 'get'
  match '/location', to: 'public_pages#location', via: 'get'

  match 'patient_record', to: 'patients#new', via: 'get'
  match 'patient_infos', to: 'patients#patient_info', via: 'post'
  match 'dental_insurances', to: 'patients#dental_insurance', via: 'post'
  match 'dental_histories', to: 'patients#dental_history', via: 'post'

  match 'lvd_employee_area77', to: 'private_pages#lakeview_emp_area77', via: 'get'
  match 'lvd_employee_area88', to: 'private_pages#lakeview_emp_area88', via: 'get'
  
  get 'lvd_emp_loggin' => 'lvd_priv_sessions#new'
  post 'lvd_emp_loggin' => 'lvd_priv_sessions#create'
  delete 'lvd_emp_logout' => 'lvd_priv_sessions#destroy'

end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def location
  end

end

app/helpers/public_pages_helper.rb
module PublicPagesHelper
end

app/views/public_pages/home.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->

  <%= render 'layouts/header' %>

    <div class="jumbotron" id="jmbotron">
      <div class="container">
   

      </div>
    </div>

    <div class="container">
 
        <!-- column 1 -->
        <%= link_to services_path do %>
          <%= render 'shared/services_card' %>
       <% end %>


       <%= link_to patient_record_path do %>
        <!-- column 2 -->
          <%= render 'shared/appointment_card' %>
       <% end %>
        

       <!-- column 3 -->
       <%= link_to location_path do %>
          <%= render 'shared/location_card' %>
        <% end %>
      

  

      
    </div> <!-- /container -->



    
    

app/views/public_pages/location.html.erb
<address class="extra_info well blue_back text-center">
Phone and Fax: (954) 752-7874<br>
Open: Monday - Thursday from 9am - 5pm
</address>
	
  <div class="bcontainer">
  
  <!-- Services card for larger screens -->      
  <%= link_to services_path, class: "small_device_hidden" do %>
    <%= render 'shared/services_card' %>
  <% end %>

  <%= render 'shared/gmaps_card' %>

  <%= link_to patient_record_path do %>
   <%= render 'shared/appointment_card' %>
  <% end %>

  <!-- Services card for smaller screens -->
  <%= link_to services_path, class: "small_device_shown" do %>
   <%= render 'shared/services_card' %>
  <% end %>

</div>
<style>body {margin: 0;}</style>

app/views/public_pages/services.html.erb
 
<header class="extra_info well lblue_back text-center">
  <h1>LakeView Dental Services</h1>
</header>

 <div class="bcontainer">
  
  <!-- Services card for larger screens -->      
  <%= link_to location_path, class: "small_device_hidden" do %>
    <%= render 'shared/location_card' %>
  <% end %>

  <%= render 'shared/services_list_card' %>

  <%= link_to patient_record_path do %>
   <%= render 'shared/appointment_card' %>
  <% end %>

  <!-- Services card for smaller screens -->
  <%= link_to location_path, class: "small_device_shown" do %>
   <%= render 'shared/location_card' %>
  <% end %>

</div>
<style type="text/css">body {margin:0;}</style>